import type { Account, Transaction } from '../types/domain';
import { getCategory } from '../domain/categories';
import { spendingTreatment, TREATMENT_LABELS } from '../classification/spending';

/**
 * The cleaned CSV export.
 *
 * Pure string construction, deliberately separated from anything that touches
 * the browser. Nothing here creates a Blob, an object URL, or a download — that
 * lives in `downloadCsv` below and can be tested independently, which is what
 * lets the *contents* be asserted against malicious fixtures rather than the
 * existence of a button.
 *
 * Two hazards shape this file:
 *
 *  1. **Spreadsheet formula injection.** A description reading `=cmd|...` is
 *     data here and an executable formula in Excel. Every user-controlled cell
 *     is neutralized; every app-generated one is not, because prefixing an
 *     amount would corrupt the number.
 *  2. **Precision.** Amounts are integer cents throughout the product, and the
 *     conversion below stays integer arithmetic. A `cents / 100` would
 *     reintroduce exactly the floating-point error the calculation contract
 *     forbids.
 */

/** Characters that make a spreadsheet treat a cell as a formula. */
const FORMULA_TRIGGERS = new Set(['=', '+', '-', '@']);

/** Control characters that can begin a formula after a paste. */
const CONTROL_TRIGGERS = new Set(['\t', '\r', '\n']);

/**
 * Neutralizes a user-controlled cell.
 *
 * The trigger is looked for **after leading whitespace**, because a spreadsheet
 * trims before deciding, so `   =1+1` is every bit as executable as `=1+1`. The
 * mitigation is a leading apostrophe, which spreadsheets read as "this is text"
 * and strip on display.
 *
 * Applied only to text a person can influence. Amounts, dates, and enum values
 * are generated by this application and are left exactly as produced — a
 * negative amount legitimately begins with `-`.
 */
export function neutralizeCell(value: string): string {
  if (value.length === 0) return value;

  // Checked before any trimming, because tab is *both* whitespace and a
  // trigger. Trimming all whitespace first would silently consume the very
  // character being defended against - which is what this originally did.
  if (CONTROL_TRIGGERS.has(value[0]!)) return `'${value}`;

  // Only literal spaces are trimmed. A spreadsheet trims before deciding
  // whether a cell is a formula, so a space-padded `=1+1` is still a formula.
  const firstMeaningful = value.replace(/^ +/, '');
  if (firstMeaningful.length === 0) return value;

  const lead = firstMeaningful[0]!;
  if (FORMULA_TRIGGERS.has(lead) || CONTROL_TRIGGERS.has(lead)) return `'${value}`;

  // A cell that *begins* with a control character is caught above; one that
  // merely contains a newline is handled by RFC quoting, not by prefixing.
  return value;
}

/**
 * RFC 4180 quoting.
 *
 * A field is quoted when it contains a delimiter, a quote, or a line break, and
 * internal quotes are doubled. Applied after neutralization so the apostrophe
 * is inside the quoted field rather than outside it.
 */
export function quoteCsvField(value: string): string {
  if (!/[",\r\n]/.test(value)) return value;
  return `"${value.replace(/"/g, '""')}"`;
}

/** Integer cents to a signed decimal string, without floating-point division. */
export function formatAmount(amountCents: number, direction: 'debit' | 'credit'): string {
  const magnitude = Math.abs(Math.trunc(amountCents));
  const whole = Math.floor(magnitude / 100);
  const fraction = String(magnitude % 100).padStart(2, '0');
  const sign = direction === 'debit' ? '-' : '';
  return `${sign}${whole}.${fraction}`;
}

/**
 * The column order, fixed.
 *
 * Deterministic so two exports of the same data are byte-identical and a
 * spreadsheet template built against one keeps working.
 */
export const CSV_COLUMNS = [
  'Posted date',
  'Account',
  'Raw description',
  'Merchant',
  'Amount',
  'Direction',
  'Kind',
  'Category',
  'Spending treatment',
  'Exclusion reason',
  'Essentiality',
  'Variability',
  'Tags',
  'Note',
  'Import session',
] as const;

/** Cells the user can influence, and which therefore get neutralized. */
const USER_CONTROLLED = new Set<(typeof CSV_COLUMNS)[number]>([
  'Account',
  'Raw description',
  'Merchant',
  'Tags',
  'Note',
]);

export interface CsvExportInput {
  readonly transactions: readonly Transaction[];
  readonly accounts: readonly Account[];
}

function rowFor(
  transaction: Transaction,
  accountLabels: ReadonlyMap<string, string>,
): readonly string[] {
  const treatment = spendingTreatment(transaction);

  return [
    transaction.postedDate,
    accountLabels.get(transaction.accountId) ?? transaction.accountId,
    transaction.descriptionRaw,
    transaction.merchantNormalized,
    formatAmount(transaction.amountCents, transaction.direction),
    transaction.direction,
    transaction.kind,
    getCategory(transaction.categoryId)?.label ?? transaction.categoryId,
    TREATMENT_LABELS[treatment],
    transaction.exclusionReason ?? '',
    transaction.essentiality ?? '',
    transaction.variability ?? '',
    transaction.tags.join('; '),
    transaction.note ?? '',
    transaction.importSessionId,
  ];
}

/**
 * Builds the CSV text for a set of transactions.
 *
 * Rows come out in a deterministic order — posting date, then id — regardless
 * of the order they arrived in, so an export is reproducible.
 */
export function buildCleanedCsv(input: CsvExportInput): string {
  const accountLabels = new Map(input.accounts.map((account) => [account.id, account.label]));

  const ordered = [...input.transactions].sort(
    (a, b) => a.postedDate.localeCompare(b.postedDate) || a.id.localeCompare(b.id),
  );

  const lines: string[] = [CSV_COLUMNS.map(quoteCsvField).join(',')];

  for (const transaction of ordered) {
    const cells = rowFor(transaction, accountLabels);
    lines.push(
      cells
        .map((cell, index) => {
          const column = CSV_COLUMNS[index]!;
          const prepared = USER_CONTROLLED.has(column) ? neutralizeCell(cell) : cell;
          return quoteCsvField(prepared);
        })
        .join(','),
    );
  }

  // CRLF is what RFC 4180 specifies and what spreadsheets expect.
  return `${lines.join('\r\n')}\r\n`;
}

/**
 * A filename carrying no personal value.
 *
 * Deliberately not built from an account label, a merchant, or a filter. A
 * download lands in a shared folder and its name is visible to anyone who can
 * see the directory; naming it after what it contains would leak exactly the
 * thing the rest of this product keeps local.
 */
export function cleanedCsvFilename(exportedAt: string): string {
  const day = /^\d{4}-\d{2}-\d{2}/.exec(exportedAt)?.[0] ?? 'export';
  return `tri-state-spending-lens-transactions-${day}.csv`;
}

export type CsvExportFailureReason = 'nothing-to-export' | 'export-failed';

export interface CsvExportRejection {
  readonly ok: false;
  readonly reason: CsvExportFailureReason;
  readonly message: string;
}

export interface CsvExportSuccess {
  readonly ok: true;
  readonly csv: string;
  readonly filename: string;
  readonly rowCount: number;
}

export type CsvExportResult = CsvExportSuccess | CsvExportRejection;

const EXPORT_MESSAGES: Record<CsvExportFailureReason, string> = {
  'nothing-to-export': 'There are no transactions to export with these filters.',
  'export-failed': 'The export could not be produced. Nothing was changed or saved.',
};

/** Builds an export result without touching the browser or the database. */
export function buildCsvExport(input: CsvExportInput, exportedAt: string): CsvExportResult {
  if (input.transactions.length === 0) {
    return {
      ok: false,
      reason: 'nothing-to-export',
      message: EXPORT_MESSAGES['nothing-to-export'],
    };
  }

  try {
    return {
      ok: true,
      csv: buildCleanedCsv(input),
      filename: cleanedCsvFilename(exportedAt),
      rowCount: input.transactions.length,
    };
  } catch {
    return { ok: false, reason: 'export-failed', message: EXPORT_MESSAGES['export-failed'] };
  }
}

/* ---------------------------------------------------------- downloading - */

export interface DownloadPorts {
  readonly createObjectURL: (blob: Blob) => string;
  readonly revokeObjectURL: (url: string) => void;
  readonly click: (url: string, filename: string) => void;
}

/**
 * Hands a built CSV to the browser.
 *
 * Separate from construction so the contents can be asserted without a DOM, and
 * so the object-URL lifecycle is testable in isolation. The URL is revoked in a
 * `finally`: a leaked blob URL keeps the whole CSV — every transaction the user
 * has — alive in memory for the lifetime of the document.
 *
 * The CSV itself is never stored, never logged, and never sent anywhere.
 */
export function downloadCsv(csv: string, filename: string, ports: DownloadPorts): void {
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = ports.createObjectURL(blob);
  try {
    ports.click(url, filename);
  } finally {
    ports.revokeObjectURL(url);
  }
}

/** The production ports, wired to the real browser. */
export function browserDownloadPorts(): DownloadPorts {
  return {
    createObjectURL: (blob) => URL.createObjectURL(blob),
    revokeObjectURL: (url) => {
      URL.revokeObjectURL(url);
    },
    click: (url, filename) => {
      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = filename;
      anchor.rel = 'noopener';
      document.body.append(anchor);
      anchor.click();
      anchor.remove();
    },
  };
}
